# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"
    - name: Get swift version
      run: swift --version
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: SwiftFormat
      run: swiftformat --swiftversion 6.0 --lint . --reporter github-actions-log
    - name: Run tests
      run: swift test -v
