# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Homebrew/actions/setup-homebrew@master
    - uses: swift-actions/setup-swift@v2
      with:
        # Uses of Swift 6 for Swift Testing
        swift-version: "6.0"
    - name: Show macOS version
      run: sw_vers --productVersion
    - name: Show Swift version
      run: swift --version
    - name: Setup linters
      run: brew install swiftlint
    - name: SwiftLint
      run: swiftlint --strict
    - name: SwiftFormat
      run: swiftformat . --reporter github-actions-log
    - name: Run tests
      run: swift test -v
